# Generated by Django 5.0.6 on 2024-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_alter_rubric_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена'),
        ),
    ]
